apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.chromadb.appName}}-deployment"
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.chromadb.appName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.chromadb.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.chromadb.appName}}
    spec:
      containers:
      - name: chromadb
        image: {{.Values.chromadb.image}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{.Values.chromadb.containerPort}}
          name: http
        resources:
          requests:
            memory: {{.Values.chromadb.requests.memory | quote}}
            cpu: {{.Values.chromadb.requests.cpu | quote}}
          limits:
            memory: {{.Values.chromadb.limits.memory | quote}}
            cpu: {{.Values.chromadb.limits.cpu | quote}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.chromadb.serviceName}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.chromadb.appName}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.chromadb.appName}}
  ports:
  - port: {{.Values.chromadb.servicePort}}
    targetPort: http
    protocol: TCP
    name: http
