apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fairscape.backend.appName }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fairscape.backend.appName}}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: prod-fairscape
  template:
    metadata:
      labels:
        app: prod-fairscape
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: fairscape
        image: {{ .Values.fairscape.backend.image }} 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        {{- /*
        generate env variables from values configuration
        */}}
        - name: "FAIRSCAPE_MONGO_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo.accessKey.secretName | quote }}
              key: {{ .Values.mongo.accessKey.secretKey | quote }} 
        - name: "FAIRSCAPE_MONGO_SECRET_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo.secretKey.secretName | quote }}
              key: {{ .Values.mongo.secretKey.secretKey | quote }} 
        - name: "FAIRSCAPE_MINIO_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.minio.accessKey.secretName | quote }}
              key: {{ .Values.minio.accessKey.secretKey | quote }} 
        - name: "FAIRSCAPE_MINIO_SECRET_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.minio.secretKey.secretName | quote }}
              key: {{ .Values.minio.secretKey.secretKey | quote }} 
        - name: "FAIRSCAPE_MINIO_URI"
          value: {{ .Values.minio.serviceName }}
        - name: "FAIRSCAPE_REDIS_HOST"
          value: {{ .Values.redis.serviceName }}
        - name: "FAIRSCAPE_REDIS_PORT"
          value: {{ .Values.redis.servicePort}}
        - name: "FAIRSCAPE_REDIS_DATABASE"
          value: {{ .Values.redis.jobDatabase }}
        - name: "FAIRSCAPE_REDIS_RESULT_DATABASE"
          value: {{ .Values.redis.resultDatabase }}
        {{- range $envVar := .Values.fairscapeConfig.env}}
        - name: {{ $envVar.name }}
          value: {{ $envVar.value }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.fairscape.backend.requests.memory | quote }}
            cpu: {{ .Values.fairscape.backend.requests.cpu | quote }}
          limits:
            memory: {{ .Values.fairscape.backend.limits.memory | quote }}
            cpu: {{ .Values.fairscape.backend.limits.cpu | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fairscape.backend.appName }}-service 
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fairscape.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.fairscape.backend.appName }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fairscape.worker.appName}}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fairscape.worker.appName }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: prod-fairscape
  template:
    metadata:
      labels:
        app: prod-fairscape
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: fairscape
        image: {{ .Values.fairscape.worker.image }} 
        imagePullPolicy: Always
        command: ["python"] 
        args: ["fairscape_mds/worker.py" ]
        #livenessProbe:
        #  httpGet:
        #    path: /healthz
        #    port: 80
        #  initialDelaySeconds: 3
        #  periodSeconds: 3
        env:
        - name: FAIRSCAPE_HOST
          value: 'fairscape.net'
        - name: FAIRSCAPE_MONGO_HOST
          value: "mongo-backend-service"
        - name: FAIRSCAPE_MONGO_HOST
          value: "mongo-backend-service"
        - name: FAIRSCAPE_MONGO_DATABASE
          value: "clarklab"
        - name: FAIRSCAPE_MONGO_IDENTIFIER_COLLECTION
          value: "fairscape"
        - name: FAIRSCAPE_MONGO_USER_COLLECTION
          value: "users"
        - name: FAIRSCAPE_MONGO_ROCRATE_COLLECTION
          value: "rocrate"
        - name: FAIRSCAPE_MONGO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: fairscape-secrets
              key: mongo-access-key
        - name: FAIRSCAPE_MONGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fairscape-secrets
              key: mongo-secret-key
        - name: FAIRSCAPE_MINIO_URI
          value: "minio.uvarc.io"
        - name: FAIRSCAPE_MINIO_SECURE
          value: "True"
        - name: FAIRSCAPE_MINIO_CERT_CHECK
          value: "False"
        - name: FAIRSCAPE_MINIO_DEFAULT_BUCKET
          value: "clarklab"
        - name: FAIRSCAPE_MINIO_DEFAULT_BUCKET_PATH
          value: "fairscape"
        - name: FAIRSCAPE_MINIO_ROCRATE_BUCKET
          value: "clarklab"
        - name: FAIRSCAPE_MINIO_ROCRATE_BUCKET_PATH
          value: "fairscape"
        - name: FAIRSCAPE_MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: fairscape-secrets
              key: minio-access-key
        - name: FAIRSCAPE_MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fairscape-secrets
              key: minio-secret-key
        - name: FAIRSCAPE_JWT_SECRET
          value: "jwt-secret"
        - name: FAIRSCAPE_NAAN
          value: "59852"
        - name: FAIRSCAPE_PASSWORD_SALT
          value: "testsalt"
        - name: FAIRSCAPE_REDIS_HOST
          value: "prod-redis-service"
        - name: FAIRSCAPE_REDIS_PORT
          value: "6379"
        - name: FAIRSCAPE_REDIS_DATABASE
          value: "0"
        - name: FAIRSCAPE_REDIS_RESULT_DATABASE
          value: "1"
        - name: FAIRSCAPE_LDAP_HOST
          value: "prod-ldap-service"
        - name: FAIRSCAPE_LDAP_PORT
          value: "1389"
        - name: FAIRSCAPE_LDAP_BASE_DN
          value: "dc=fairscape,dc=net"
        - name: FAIRSCAPE_LDAP_USERS_DN
          value: "ou=users,dc=fairscape,dc=net"
        - name: FAIRSCAPE_LDAP_GROUPS_DN
          value: "ou=groups,dc=fairscape,dc=net"
        - name: FAIRSCAPE_LDAP_ADMIN_DN
          value: "cn=fairscapeAdmin,dc=fairscape,dc=net"
        - name: FAIRSCAPE_LDAP_ADMIN_PASSWORD
          value: "fJU#U1M62FnJyH#B1#9P"
        resources:
          requests:
            memory: {{ .Values.fairscape.worker.requests.memory | quote }}
            cpu: {{ .Values.fairscape.worker.requests.cpu | quote }}
          limits:
            memory: {{ .Values.fairscape.worker.limits.memory | quote }}
            cpu: {{ .Values.fairscape.worker.limits.cpu | quote }}
      serviceAccountName: fairscape-sa 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fairscape.frontend.appName }}-deployment
  namespace: clarklab
  labels:
    app: {{ .Values.fairscape.frontend.appName }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.fairscape.frontend.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.fairscape.frontend.appName }}
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: fairscape-frontend
        image: {{ .Values.fairscape.frontend.image }} 
        ports:
        - containerPort: {{ .Values.fairscape.frontend.serviceTargetPort }}
        resources:
          requests:
            memory: {{ .Values.fairscape.frontend.requests.memory | quote }}
            cpu: {{ .Values.fairscape.frontend.requests.cpu | quote }}
          limits:
            memory: {{ .Values.fairscape.frontend.limits.memory | quote }}
            cpu: {{ .Values.fairscape.frontend.limits.cpu | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fairscape.frontend.appName }}-service
  namespace: clarklab
  labels:
    app: {{ .Values.fairscape.frontend.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.fairscape.frontend.appName }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.fairscape.frontend.servicePort }}
      targetPort: {{ .Values.fairscape.frontend.serviceTargetPort }}
