apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    #cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    # enable https passthrough
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    # set a 1hr timeout for sending proxied request to server
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.org/proxy-send-timeout: "3600"
    nginx.org/proxy-read-timeout: "3600"
    proxy-send-timeout: "3600"
    proxy-read-timeout: "3600"
    # set max body size to 5Gi
    nginx.ingress.kubernetes.io/client-max-body-size: "5000M"
    nginx.org/client-max-body-size: "5000M"
    client-max-body-size: "5000M"
    # turn off proxy buffering
    nginx.org/proxy-buffering: "false"
  name: fairscape-ingress
  namespace: clarklab
spec:
  rules:

    - host: "me.fairscape.net"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: {{ .Values.mongo_express.serviceName}}
              port:
                number: {{ .Values.mongo_express.servicePort}}
    - host: "test.fairscape.net"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: "test-{{ .Values.fairscape.frontend.serviceName }}"
              port:
                number: {{ .Values.fairscape.frontend.servicePort }}
        - pathType: Prefix
          path: "/api"
          backend:
            service:
              name: "test-{{ .Values.fairscape.backend.serviceName }}"

              port:
                number: {{ .Values.fairscape.backend.servicePort }}

    - host: "fairscape.net"
      http:
        paths:
        - pathType: Prefix
          path: "/api"
          backend:
            service:
              name: "prod-{{ .Values.fairscape.backend.serviceName }}"

              port:
                number: {{ .Values.fairscape.backend.servicePort }}
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: {{ .Values.fairscape.frontend.serviceName }}
              port:
                number: {{ .Values.fairscape.frontend.servicePort }}
    - host: "www.fairscape.net"
      http:
        paths:
        - pathType: Prefix
          path: "/api"
          backend:
            service:
              name: "prod-{{ .Values.fairscape.backend.serviceName }}"
              port:
                number: {{ .Values.fairscape.backend.servicePort }}
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: {{ .Values.fairscape.frontend.serviceName }}
              port:
                number: {{ .Values.fairscape.frontend.servicePort }}


    # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
      - "fairscape.net"
      - "www.fairscape.net"
      - "test.fairscape.net"
      secretName: star-fairscape-tls
      # fairscape-net-tls-secret
