apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # enable https passthrough
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    # set a 1hr timeout for sending proxied request to server
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.org/proxy-send-timeout: "3600"
    nginx.org/proxy-read-timeout: "3600"
    proxy-send-timeout: "3600"
    proxy-read-timeout: "3600"
    # set max body size to 5Gi
    nginx.ingress.kubernetes.io/client-max-body-size: "5000M"
    nginx.org/client-max-body-size: "5000M"
    client-max-body-size: "5000M"
    # turn off proxy buffering
    nginx.org/proxy-buffering: "false"
  name: fairscape-ingress
  namespace: clarklab
spec:
  rules:
    #- host: test.fairscape.net
    #  http:
    #    paths:
    #      - pathType: Prefix
    #        path: "/"
    #        backend:
    #          service:
    #            name: test-fairscape-service
    #            port:
    #              number: 80
    - host: fairscape.net
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: test-fairscape-service
                port:
                  number: 443


    # This section is only required if TLS is to be enabled for the Ingress
    #  tls:
    #  - hosts:
    #      - fairscape.net
    #    secretName: fairscape-net-sealed-secret
