apiVersion: v1
kind: Service
metadata:
  name: fairscape-service
  namespace: clarklab
spec:
  selector:
    app: fairscape
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
