apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/client-max-body-size: "1000m"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    #nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    #nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "50m"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
# annotations for jupyterhub websockets
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#    nginx.org/websocket-services: "fairscape-service"
  name: fairscape-ingress
  namespace: clarklab
spec:
  rules:
    - host: fairscape.pods.uvarc.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: fairscape-service
                port:
                  number: 80
    # This section is only required if TLS is to be enabled for the Ingress
  tls:
      - hosts:
          - fairscape.pods.uvarc.io
        secretName: fairscape-nginx-tls-ingress-secret
