apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub-deployment
  namespace: clarklab
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.jupyterhub.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.jupyterhub.appName }}
    spec:
      containers:
      - name: jupyterhub
        image: {{ .Values.jupyterhub.image }}
        command: 
        - "start-notebook.sh"
        - "--ServerApp.ip='*'"
        - "--ServerApp.allow_remote_access=True"
        - "--ServerApp.port=8888"
        - "--ServerApp.open_browser=False"
        - "--NotebookApp.allow_origin='https://jupyterhub.fairscape.pods.uvarc.io'"
        ports:
        - name: http
          containerPort: 8888
        securityContext:
          # jovyan uid 1000
          runAsUser: 1000 
          # jovyan gid 100
          runAsGroup: 100
          # allow jovyan to sudo
          fsGroup: 100
          allowPrivilegeEscalation: true
        env:
        - name: "FAIRSCAPE_MONGO_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo.accessKey.secretName | quote }}
              key: {{ .Values.mongo.accessKey.secretKey | quote }}
        - name: "FAIRSCAPE_MONGO_SECRET_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo.secretKey.secretName | quote }}
              key: {{ .Values.mongo.secretKey.secretKey | quote }}
        - name: "FAIRSCAPE_MINIO_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.minio.accessKey.secretName | quote }}
              key: {{ .Values.minio.accessKey.secretKey | quote }}
        - name: "FAIRSCPAE_MINIO_SECRET_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.minio.secretKey.secretName | quote }}
              key: {{ .Values.minio.secretKey.secretKey | quote }}
        {{- range $envVar := .Values.fairscapeConfig.env}}
        - name: {{ $envVar.name | quote }}
          value: {{ $envVar.value | quote }}
        {{- end }}
        # allow jovyan to sudo
        - name: GRANT_SUDO
          value: "yes" 
        resources:
          requests:
            memory: {{ .Values.jupyterhub.requests.memory | quote }}
            cpu: {{ .Values.jupyterhub.requests.cpu | quote }}
          limits:
            memory: {{ .Values.jupyterhub.limits.memory | quote }}
            cpu: {{ .Values.jupyterhub.limits.cpu | quote }}
      serviceAccountName: fairscape-sa 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jupyterhub.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.jupyterhub.appName }}
spec:
  selector:
    app: {{ .Values.jupyterhub.appName }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyterhub-fairscape-ingress
  namespace: clarklab
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    acme.cert-manager.io/http01-edit-in-place: "true"
# annotations for jupyterhub websockets
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.org/websocket-services: {{ .Values.jupyterhub.serviceName }}
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
spec:
  rules:
    - host: jupyterhub.fairscape.pods.uvarc.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Values.jupyterhub.serviceName }}
                port:
                  number: 80 
    # This section is only required if TLS is to be enabled for the Ingress
  tls:
      - hosts:
          - jupyterhub.fairscape.pods.uvarc.io
        secretName: jupyterhub-fairscape-nginx-tls-ingress-secret
