apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  
  name: jupyterhub-ingress
  namespace: clarklab
spec:
  rules:
    - host: jupyter.fairscape.pods.uvarc.io
      http:
        paths:
          - backend:
              serviceName: jupyterhub-service
              servicePort: 80
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
      - jupyter.fairscape.pods.uvarc.io
      secretName: fairscape-tls-ingress-secret
