
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /

  name: jupyterhub-ingress
  namespace: clarklab
spec:
  rules:
    - host: jupyterhub.fairscape.pods.uvarc.io
      http:
        paths:
          - backend:
              serviceName: jupyterhub-service
              servicePort: 80
            path: /
      
    # This section is only required if TLS is to be enabled for the Ingress
  tls:
      - hosts:
          - jupyterhub.fairscape.pods.uvarc.io
        secretName: fairscape-tls-ingress-secret
