apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub-deployment
  namespace: clarklab
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
      - name: jupyterhub
        image: jupyter/datascience-notebook
        command: 
        - "start-notebook.sh"
        - "--ServerApp.ip='*'"
        - "--ServerApp.allow_remote_access=True"
        - "--ServerApp.port=8888"
        - "--ServerApp.open_browser=False"
        - "--NotebookApp.allow_origin='https://jupyterhub.fairscape.pods.uvarc.io'"
        env:
        - name: "NOTEBOOK_ARGS"
          value: "--log-level='DEBUG'"
        ports:
        - name: http
          containerPort: 8888
        resources:
          requests:
            memory: "6024Mi"
            cpu: "250m"
          limits:
            memory: "8024Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/home/jovyan/work"
          name: notebook-storage
        - name: tls-credentials
          mountPath: "/etc/tls-cred"
      volumes:
      - name: notebook-storage
        persistentVolumeClaim:
          claimName: jupyterhub-pvc
      - name: tls-credentials
        secret:
          secretName: fairscape-tls-ingress-secret