apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub-deployment
  namespace: clarklab
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      securityContext:
        runAsUser: 1000 
        fsGroup: 1000
      containers:
      - name: jupyterhub
        image: jupyter/datascience-notebook:2022-09-29
        ports:
        - name: http
          containerPort: 8888
        resources:
          requests:
            memory: "6024Mi"
            cpu: "250m"
          limits:
            memory: "8024Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/home/jovyan/work"
          name: notebook-storage
        - mountPath: "/home/jovyan/config"
          name: jupyter-config
      volumes:
      - name: notebook-storage
        persistentVolumeClaim:
          claimName: jupyterhub-pvc
      - name: jupyter-config
        configMap:
          name: jupyterhub-configmap
          items:
          - key: jupyter_notebook_config.py
            path: jupyter_notebook_config.py