apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub-deployment
  namespace: clarklab
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      initContainers:
      - name: copy-tls
        image: busybox
        command: ["sh", "-c", "cp -R /etc/tls-cred/ /home/jovyan/work/tls-cred && chown -R 1000:1000 /home/jovyan/work/tls-cred"]
        resources:
          requests:
            memory: "500Mi"
            cpu: "100m"
          limits:
            memory: "1000Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: "/home/jovyan/work"
          name: notebook-storage
        - name: tls-credentials
          mountPath: "/etc/tls-cred"
      containers:
      - name: jupyterhub
        image: jupyter/datascience-notebook
        command: 
        - "start-notebook.sh"
        - "--ServerApp.keyfile=/home/jovyan/tls.key"
        - "--ServerApp.certfile=/home/jovyan/tls.crt"
        - "--ServerApp.ip='*'"
        - "--ServerApp.allow_remote_access=True"
        - "--ServerApp.port=8888"
        - "--ServerApp.open_browser=False"
        env:
        - name: "GRANT_SUDO"
          value: "yes"
        ports:
        - name: http
          containerPort: 8888
        resources:
          requests:
            memory: "6024Mi"
            cpu: "250m"
          limits:
            memory: "8024Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/home/jovyan/work"
          name: notebook-storage
        - name: tls-credentials
          mountPath: "/etc/tls-cred"
      volumes:
      - name: notebook-storage
        persistentVolumeClaim:
          claimName: jupyterhub-pvc
      - name: tls-credentials
        secret:
          secretName: fairscape-tls-ingress-secret