apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub-deployment
  namespace: clarklab
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      securityContext:
        runAsUser: 1000 
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /secrets"]
          volumeMounts:
          - name: tls-credentials
            mountPath: /secrets
      containers:
      - name: jupyterhub
        image: jackofsum/jupyter_test:0.0.1
        ports:
        - name: http
          containerPort: 8888
        resources:
          requests:
            memory: "6024Mi"
            cpu: "250m"
          limits:
            memory: "8024Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/home/jovyan/work"
          name: notebook-storage
        - name: tls-credentials
          readOnly: true
          mountPath: "/etc/tls-cred"
      volumes:
      - name: notebook-storage
        persistentVolumeClaim:
          claimName: jupyterhub-pvc
      - name: tls-credentials
        secret:
          secretName: fairscape-tls-ingress-secret