apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub-deployment
  namespace: clarklab
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
      - name: jupyterhub
        image: jupyter/datascience-notebook
        command: 
        - "start-notebook.sh"
        - "--ServerApp.ip='*'"
        - "--ServerApp.allow_remote_access=True"
        - "--ServerApp.port=8888"
        - "--ServerApp.open_browser=False"
        - "--NotebookApp.allow_origin='https://jupyterhub.fairscape.pods.uvarc.io'"
        ports:
        - name: http
          containerPort: 8888
        env:
        - name: MINIO_URI
          value: minio.pods.uvarc.io
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_SECURE
          value: "False"
        - name: MINIO_DEFAULT_BUCKET
          value: clarklab
        - name: MINIO_ROCRATE_BUCKET
          value: clarklab
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: fairscape-secrets
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fairscape-secrets
              key: minio-secret-key
        resources:
          requests:
            memory: "6024Mi"
            cpu: "250m"
          limits:
            memory: "8024Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/home/jovyan/work"
          name: notebook-storage
        - mountPath: "/home/jovyan/project"
          name: nfs-project-storage
      serviceAccountName: fairscape-sa 
      volumes:
      - name: nfs-project-storage 
        nfs:
          server: "qumulo.rc.virginia.edu"
          path: "/clarklab"
      - name: notebook-storage
        persistentVolumeClaim:
          claimName: jupyterhub-pvc