apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ldap.appName }}-deployment
  namespace: clarklab
  labels:
    app: {{ .Values.ldap.appName }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.ldap.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.ldap.appName }}
    spec:
      containers:
      - name: ldap
        image: {{ .Values.ldap.image}} 
        imagePullPolicy: Always
        ports:
        - name: db
          containerPort: {{.Values.ldap.servicePort}}
        {{- range $key, $val := .Values.ldap.env}}
        - name: {{ $key | quote }}
          value: {{ $val | quote }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.ldap.requests.memory | quote }}
            cpu: {{ .Values.ldap.requests.cpu | quote }}
          limits:
            memory: {{ .Values.ldap.limits.memory | quote }}
            cpu: {{ .Values.ldap.limits.cpu | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ldap.appName}}-service
  namespace: clarklab
  labels:
    app: {{ .Values.ldap.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.ldap.appName }}
  ports:
    - name: http
      protocol: TCP
      port: {{.Values.ldap.servicePort}}
      targetPort: {{.Values.ldap.servicePort}}

