---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.fairscape.minio.volume.pvcName | quote }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fairscape.minio.appName }}
spec:
  storageClassName: {{ .Values.fairscape.minio.volume.storageClassName }}
  volumeName: {{ .Values.fairscape.minio.volume.volumeName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.fairscape.minio.volume.storage }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fairscape.minio.appName}}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels: 
      app: {{ .Values.fairscape.minio.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.fairscape.minio.appName }}
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      volumes:
      - name: project-volume
        persistentVolumeClaim:
          claimName: {{ .Values.fairscape.minio.volume.pvcName | quote}}
      containers:
      - name: minio
        image: {{ .Values.fairscape.minio.image }}
        command: ["minio", "server", "/data/Fairscape", "--console-address", ":9001"]
        ports:
        - containerPort: {{ .Values.fairscape.minio.serviceTargetPort }}
        resources:
          requests:
            memory: {{ .Values.fairscape.minio.requests.memory | quote }}
            cpu: {{ .Values.fairscape.minio.requests.cpu | quote }}
          limits:
            memory: {{ .Values.fairscape.minio.limits.memory | quote }}
            cpu: {{ .Values.fairscape.minio.limits.cpu | quote }}
        volumeMounts:
        - mountPath: "/data"
          name: project-volume
        env:
        - name: "MINIO_ROOT_USER"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.minio.accessKey.secretName | quote }}
              key: {{ .Values.minio.accessKey.secretKey | quote }} 
        - name: "MINIO_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.minio.secretKey.secretName | quote }}
              key: {{ .Values.minio.secretKey.secretKey | quote }} 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fairscape.minio.serviceName}}
  namespace: {{ .Values.namespace}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.fairscape.minio.appName }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.fairscape.minio.servicePort }}
      targetPort: {{ .Values.fairscape.minio.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.fairscape.minio.serviceName}}-console"
  namespace: {{ .Values.namespace}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.fairscape.minio.appName }}
  ports:
    - name: http
      protocol: TCP
      port: 9001 
      targetPort: 9001