apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: clarklab
spec:
  selector:
    app: mongo
  ports:
    - name: mongo 
      protocol: TCP
      port: 27017
      targetPort: 27017
