apiVersion: apps/v1
kind: Deployment
metadata:
  name: "prod-{{ .Values.mongo_express.appName }}-deployment"
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.mongo_express.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo_express.appName }}
    spec:
      containers:
      - name: mongo-express 
        image: {{ .Values.mongo_express.image }} 
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: {{ .Values.mongo_express.requests.memory | quote }}
            cpu: {{ .Values.mongo_express.requests.cpu | quote }}
          limits:
            memory: {{ .Values.mongo_express.limits.memory | quote }}
            cpu: {{ .Values.mongo_express.limits.cpu | quote }}
        env:
        - name: "ME_CONFIG_MONGODB_SERVER"
          value: "prod-mongo-psmdb-db-rs0"
        - name: "ME_CONFIG_MONGODB_URL"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo_express.secretName | quote }}
              key: "connectionURI" 
        - name: "ME_CONFIG_BASICAUTH_USERNAME"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo_express.secretName | quote }}
              key: "username" 
        - name: "ME_CONFIG_BASICAUTH_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo_express.secretName | quote }}
              key: "username" 
        - name: "ME_CONFIG_MONGODB_ENABLE_ADMIN"
          value: "false"
        - name: "ME_CONFIG_MONGODB_AUTH_DATABASE"
          value: "clarklab"
        - name: "ME_CONFIG_MONGODB_AUTH_USERNAME"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo.prod.username.secretName}}
              key: {{ .Values.mongo.prod.username.secretKey}}
        - name: "ME_CONFIG_MONGODB_AUTH_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo.prod.password.secretName}}
              key: {{ .Values.mongo.prod.password.secretKey}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mongo_express.serviceName}}
  namespace: clarklab
  labels:
    app: {{ .Values.mongo_express.appName}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.mongo_express.appName}}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.mongo_express.servicePort }}
      targetPort: {{ .Values.mongo_express.serviceTargetPort }}
