apiVersion: v1
kind: Service
metadata:
  name: mongo-backend-service
  namespace: clarklab
spec:
  selector:
    app: mongo-fairscape
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017