apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.fairscape.mongo.volume.pvcName | quote }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fairscape.mongo.appName }}
spec:
  storageClassName: {{ .Values.fairscape.mongo.volume.storageClassName }}
  #volumeName: {{ .Values.fairscape.mongo.volume.volumeName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.fairscape.mongo.volume.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fairscape.mongo.appName}}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fairscape.mongo.appName | quote }}
spec:
  replicas: {{ .Values.fairscape.mongo.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.fairscape.mongo.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.fairscape.mongo.appName }}
    spec:
      volumes:
      - name: prod-mongo-storage
        persistentVolumeClaim:
          claimName: {{ .Values.fairscape.mongo.volume.pvcName }}
      containers:
      - name: mongo
        image: {{ .Values.fairscape.mongo.image }}
        ports:
        - name: db
          containerPort: {{ .Values.mongo.port }}
        volumeMounts: 
        - mountPath: "/data/db"
          name: prod-mongo-storage
          subPath: "mongodb"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo.prod.username.secretName | quote }}
              key: {{ .Values.mongo.prod.username.secretKey | quote }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo.prod.password.secretName | quote }}
              key: {{ .Values.mongo.prod.password.secretKey | quote }}
        resources:
          requests:
            memory: {{ .Values.fairscape.mongo.requests.memory | quote }}
            cpu: {{ .Values.fairscape.mongo.requests.cpu | quote }}
          limits:
            memory: {{ .Values.fairscape.mongo.limits.memory | quote }}
            cpu: {{ .Values.fairscape.mongo.limits.cpu | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.serviceName}}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fairscape.mongo.appName }}
spec:
  selector:
    app: {{ .Values.fairscape.mongo.appName }}
  ports:
  - name: mongodb
    protocol: TCP
    port: {{ .Values.mongo.port }}
    targetPort: {{ .Values.mongo.port }}