apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: clarklab
  labels:
    app: mongo-fairscape
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-fairscape
  template:
    metadata:
      labels:
        app: mongo-fairscape
  spec:
    containers:
    - name: mongo
      image: mongo:latest
      ports:
      - name: db
        containerPort: 27017
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
          secretKeyRef:
            name: fairscape-secrets
            key: mongo-access-key
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: fairscape-secrets
            key: mongo-secret-key
      resoureces:
        requests:
          memory: "6024Mi"
          cpu: "250m"
        limits:
          memory: "8024Mi"
          cpu: "500m"
