apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-redis
  namespace: clarklab
  labels:
    app: prod-redis
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: prod-redis
  template:
    metadata:
      labels:
        app: prod-redis
    spec:
      volumes:
        - name: redis-config
          configMap:
            name: redis-configmap
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: {{ .Values.redis.servicePort }}
        volumeMounts:
        - name: redis-config
          mountPath: "/usr/local/etc/redis/redis.conf"
          readOnly: true  
        command: ["redis-server"] 
        args: ["/usr/local/etc/redis/redis.conf"]
        resources:
          requests:
            memory: {{ .Values.redis.requests.memory | quote }}
            cpu: {{ .Values.redis.requests.cpu | quote }}
          limits:
            memory: {{ .Values.redis.limits.memory | quote }}
            cpu: {{ .Values.redis.limits.cpu | quote }}
---
apiVersion: v1
data:
  redis.conf: |
    # disable snapshotting
    save ""

    # serve on port
    port 6379

    # listen on all interfaces
    bind 127.0.0.1 -::1

    # masterauth <master-password>
    # masteruser <master-username>
kind: ConfigMap
metadata:
  namespace: clarklab
  name: redis-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName }}
  namespace: clarklab
  labels:
    app: prod-fairscape
spec:
  type: ClusterIP
  selector:
    app: prod-redis
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.servicePort }}
