---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcrPullSecret
  namespace: clarklab
spec:
  encryptedData:
    .dockerconfigjson: AgB6eWM5XttQ6LDtUUHq5FXHwnSGtHzmSnECfIh/N3/9iAboqoRnb6QSSBfT6s4BddxDtOh2xb35lfB9671kR/Av9vPN64c2I7Ic9S+B5mtFQxF3mWNXuRyROdFRmISO+MoJffHbRdgHsSFQwCUUmVkc/4lppccscdJMrrZ73OxL5fuQLAMJxGwlV82FfAqwVibxDhFDbpxqpzoLNwpHVFCK6riUM65lv2Mzi/hK5LRoOe9K7NT+e3YAA38ACn/+HRl3tmJWtLsHgpKyfYRSIN9OI9HCZPQP5d9BfMP8twoQu2aMKhfHFSadH7rHurRpuBT7EC0/0amM3uMUzz6v5yrfQYBtY6h8/hp4nqG9vSHdZr+dgKtGkk78/trbmVmtxsn1FzXI9o2l/z5gnJqZEXC2KdgcPDyjVKLchSlHpemcuRxo5Me1adJosmGy7Xlkrm7/NVxXvWwPsrRHC2lMjld4tluej4x47v2HDQYw/q6UXgXljJ604q8Le4EShAQxhHOS+7llwnKk8osRw/QCZcQpjoDtG7OzUFySz6w54mjQSmx8/7227pptE6yDbzA6dnJr+Hkvo/vRBe4gPSlRhkJPDV/R8PTAShMbbAOfI6VMycUstKf7lLXdaE/spP4AD8nZTjlwuCV8DjJ+shZJBtcSaF+OrYab0FO/241L0X2XY6V4DPiY4tc8QJAdqYgVvjvoVHRpyCz0V4nZpVYdejBIH21mbsU+Uzw5c0b46F+NhX95iiry1vgLtx0meCuWX5QdA4AYOGPeZr1BINmDhvUlr40iekWK6p4CjLqr2SveYVDCVBT0F2fOce7zsCCqavjkMKXFK4xUsh1y05s9JgMDrGsqkMQ=
  template:
    metadata:
      creationTimestamp: null
      name: ghcrPullSecret
      namespace: clarklab
    type: kubernetes.io/dockerconfigjson
