---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: clarklab
spec:
  encryptedData:
    password: AgBkTKJCvcGGcvmiIYZgC6e1apWsxO85GEMxzk/6WSdTaXPn7bl334c9v8j2O7DM9nz0tYJXL0XY4KEnjhZZYFV/iTTIWLWzngCHw6828wHjcFhMPi0kpFbQs1WMxLKUMe6Q8v9EUY5DWZMR2/9ThVQ8VU4CwoDa4vUw0vU9bDG6lyzCmKPDFPbqc1TEM9gANrTQHpFSKankXVatxp6+Oq0E4xoQs0WHy2ba9oumdnh4jVPl8+m+CTNWMW5kwk1AtaOzxkCPxXLE9FZsvUopuNn98OofPtRm1qr7WU/1bhWaN8qpruPhrbTuV9ob6fODGjOQjELpO2+Q5NX4z/h1QmDWXtB4L/2WIYEe2yeE48YdWod01NTola7kxveTgX1DS5YbWQIMkL6OML8isRfovwmIPueectMy7ZfVS0NDeQ72Atv5UsBUytk9QLAw6q1czJ01t2tOZNct7Ugf0/6vjptVkFpfNI1yOfphHtEpSczVRcZKYPIrEKPu6Z1wQeQpgy+XodFLDKCIlTBRzCNYxRNlIMhBe7UEQ+8st6JAEIkA5egDRWm6tIiW+Y8HGXlgbYktZOYFlxat6lkF5ZyKvXZ42xuCbSSNzXS9mr+w2+NubxqjDr8lKMcZ8ChW5GZ8YYlsz8fovWzz8YnOJoyteVUZUyfHrQ46kSom2T3dbFG5Lzz0R4KWA2tJqVAJ5Aoqzt0N8i8LkJBaBVvRpIN+cr3OLqw=
    username: AgCDtKoXxS6t+t655uchF3PF/PdK6clTCIWytlkFnJzZtVtdvJJ+gu3rDDZ9+ed7ViEiRzvHZBP6qm/YvzH3ofs6TI/8vGp7cQqgamyZp+CZNDZqQ3FaZ7t5dcp2z+qIVARbduiSf16eY5rnFoQdAF56I/8zrAcG+iLZ1dovoHa/k/EP9ZEBBeEP4XmnHk6TfIxtJDHF9yJcdgruB/2s4wt9a1Z06aGa3tx6EBORM/BC8gDRICBXOHKTgTCT3eDOts35yKicNmIv1Rr2YcY4SUdx9Yf26wcpOGe0JQ07Llry2Ram5tfOdEf4Q6ZqnMzYEbKRVJSlnaBzEbnihrJOcljvYXsA2FSDktrZ3rozfG2cTeTWBiC0LZvyFKsRaXJbR8PCDL4WK418q6tqPwvgaCdPXdKYkBHyXM2RjkUWMFj67e1fFmaA6LwR2ZsFEpxoshWByUN8oEUcjKmizyf6ouik/5sSSPZ3GKeJsnTTjZ4vGQaIGtMKAo41D1OtDriWiPAJlIHwDJaqi5mfvA4x4nuhZ1FqKdT2QMPs54JJh8Xid4YmQTHOg/6RQeTa6S92VYDyRWU4GPZHV3NnUtkeKZuarghzXV2PBB65eZchC+8PiIfQ1qMG3AgS7mMgtwy2WDcSPYK4oKd5Qv20neDgeCStomVOQhAGPPoU6k8cEiSYTsRR+h5KSb4hRrK08gtuq2njTdnBmDTW3rVFKa6I8nv0
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: clarklab
