---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-minio-secret
  namespace: clarklab
spec:
  encryptedData:
    password: AgDKors55aGBuhDyf4mzluZZ9Of2wGomalCIRbap/VyeNKJfrDuBMsEHhrRS1hI3AE9cxeiWwJJ9XyVFACAXJZx20EzUYr8Hqj+ioTWVFJoT32aSg5ftrwZd9spOjbgheBmGYn8xocs1EFoJx/cHbYLLLFUOxs2YjmHeGBhIXCWxEo+Dl3+ce1aDzkk3Nn3cH8AEwYNftoBHV7YsxfIGiUgl7Rz42nVuR1xmP8JqNeNmbxE54puL0KEkMPez6/bNtyMCrRZSmcK2l4vFoFd0sdl0tYzGzMxVq9lAUyD7httDcWYj2dLeMRL9X6pY4FN/nZGNedfZLMhnA56V88JIN3v1fyuM1ejF0NuBCoBoHxfxcsGrk2EdfLlCOONQd/yNhJybEYY/NuS1VZc8OGlCpJbiv4gIyNwy37OmTTkN/For2NK8z68BN6SG7J3iZfNpL8LpIdYKrChcE+0hb8KqgcdyGSP9NaB2LnBEmePdRZs0mvck/Sv8W5w057AArjmO9a/bqwQTbOoi84g4s3/mJUZ1gTljnFvovnKIitzzS82w1Q9girojgHj3aHkXq97xehHUWoHaiUV/TGPWrf/jqMJsYwtkPcAmthoV18A2ZP5e3mRwnSWmb63VAGzoEZIPxizlvW94gDHt4CzAEKc8D5zAl5GodHZCKH1RKkcVVCHGUgMacYtP64CfCkJ797aHQEjXddDq7FH1OBIATdYjLOnCSA0=
    username: AgAIgN973lZnRVf7Lj4OggvKFdHKT4huXmBaq1jSGVV+EY3pT1/e2IP0yo8kmMW2qm7ouGWePkXCgEWgM1JAvK1d4QLFAcUkoK0343FnlMsrOObgeNRKL+KHBVZMq04OLbFuahvIUeh+ern1PlBZams1fZ/f5ik77zNptsAbyw0GJ2ED39Ar3zvk+xY3YKKMlti8yK7rld+fBgczN0gDdtRhj2v0ru5+erXlkhOfTNKq/h42VKLPZV3sihgWGGRny4maapky0e4/a02Hx5z0Nc5/XQuK4yYj6EDscwbF3Sm37ych2yaU2jAwkGgCao8S/g8WgNJ39Dim2UmIgGaPfjuw4JoKhk4CM7VOSnYjQ0d1cWy5/EZFiYmyPlEesSdSA1/zAAjhV909YV1yAVEdnyr4uNavTRjgSXgzSIsCSNcOLsi24O9hXM0Vz/wWmUyxEPn1WT7FoXcQMHEY3h96vZksb25l8iFQzUYHUzPllCnhcRdmsVWwQ4KUevKViuw0R3KAjiL68AwM0FYYXi8qplGYTfzux0MgNB8q7JV9OJeS3CBEobCZbgD2Tc3H5I01kim7IqTfoaC2NYgAG6jk7KigyM+X8ILBJ3YqnixKHSkGWQxsQmR2XgcoB+6xtK+71iSYvYtZPRy7w3dy3OubcnRySDPxCP1LBzd02VV7n6gxdeF7z/TVJlBvYzUnCy/0OQ+4/59n4cvAHb1CbSvEnSY=
  template:
    metadata:
      creationTimestamp: null
      name: test-minio-secret
      namespace: clarklab
