---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-test-user
  namespace: clarklab
spec:
  encryptedData:
    password: AgDSKFUlLQ/paSQDTrKXsI2k+Zi7AT1m6MX3KlrDofVa7wHzDR5N6vOqjHnjDfmmfBbofJjnR/n3m/FkbKeWGUi7W8qcaAwDDs5PQMyZMj3jajODzr/2XxXpBcoPDlA02AllQkZvkL8cSZikMZ9rQXoeXyK/kDhJ/tQqDvQIxaHF47QrRAfTwzeK9NVy2NrEZORHd7Oquqa9fkKqTmdxEtjJvbNU9nMwYPUMEJ17nnJjTDVqI3opsLHEDOTeDCPiB9q0lBTU5nyajr1tNQFCDPKNllVgKiiJ86ZOX2YEVc/wwwJ9qL0rGO9ub4WETWyQR5K/ghcgAEVRZetJUUqwxXuyL+Q8SVqkMisYUPbBHbmQf01YMMsuapm0KNaua2MzMDLZmWGwjyWKEdDUK34Dzd9hCc5yk/YshCNtCkgJJqllXk94DhcSs/VN6aX99B4jAAFMv2mQKDVmbop8wqLFcTeH3+3WfQAja9GYecu7/tsy5Nuxus0D7EGhNyZZhrFlHC8vaS5LgFSk/yrHksjpJ22TLvDz+EuxL66OuhsyZI9JbmTuDPnfSdbXnbA2QVQ1CZS8wYjLfgcxrw6LGcKKQf1SiuoO12hiKYMgLMzYdN72hr46vebECyKt8p9LC9lKOaFSQU95xLumhrVfdcylLKLBs3SuqCCZXseZUVdfHkn9eRY2lhb5nNzhTHpSmmdhRrZVM4ipMLDGZ7axaaLEXbZoTgM=
    username: AgBINlJdrmLXHxs5MTn975LuxFkx4uSLKGA+5hHvEMFfvXLU4s8xMGhKy9jsaj2eqebPL3UyrUezr+k8tFFHOmw9XtfBOj45bKFQEjdVVXzjl9Dqwn2o/XseBrDC4LAf0UpFGhyUWIYRdhudiCVHaujxoXGiQWrCFObd0L/X9TH2zfK4VkEsvozZI4Q3Vh+PGefVXCtT6L2lIdRd6SkWnJlJhEV4xal1LrcRXhkKQKX+NJLUx69pLuMN525eVLmRzWIPktaF6nCcbDBZSokdX3zqkF7veML3v2JyYb/70824Lw0JqpcTTvHHyR6X0q8yQCpxaV/B+f2V0pxVzApP5LBW58ShRgRst0rqDCMnbg29udl2SW/FFVqJGhYv/APYpUucv0E7DiJdTzcn3VFbK0jgUmJ6D+NVcNsr5YhnI5/citGJvyCgfhjJsct2Epwwfxx3+kWelQ4jo3Ob1GE5sEKIpSqFDsZ8EepqMA78inI0OX5Oc37JmpZIob3wKjGGKQYnfFCfzOiZ6JfqdNgxPW+c3UsMFlhC7DFoVS00cWV2uKhJpE8G67mEH8sWRb6AF9GuHRBRFiEHZ8fqKnlFYE6VNVIOkFXsKyrxF9Qr72OfQDa3mR8JcvWeWxSdVEv1xnOaPp71BeFdSwM+8AAeYuz5RimCmPMJBt9s4AozeG9y6xp1zTbzQpycS6GasycYP3rcEqnI6IPEebYAj3dL5gw=
  template:
    metadata:
      creationTimestamp: null
      name: minio-test-user
      namespace: clarklab
