apiVersion: v1
kind: ServiceAccount
metadata:
  name: fairscape-sa
  namespace: clarklab

#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: fairscape-sa-secret
#  namespace: clarklab
#  annotations:
#    kubernetes.io/service-account.name: fairscape-secret
#type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata:
  name: fairscape-role
  namespace: clarklab
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "watch", "list", "update"]
- apiGroups: [""]
  resources: ["pods","pods/log", "persistentvolumeclaims", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "delete", "create", "update"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fairscape-rolebinding
  namespace: clarklab
subjects:
- kind: ServiceAccount
  name: fairscape-sa
  namespace: clarklab
roleRef:
  kind: Role
  name: fairscape-role
  apiGroup: rbac.authorization.k8s.io
