namespace: "clarklab"

jupyterhub:
  image: "jupyter/datascience-notebook:latest"
  serviceName: "dev-jupyterhub"
  servicePort: 8080
  serviceTargetPort: 8080
  deploymentName: "dev-jupyterhub-deployment"
  appName: "dev-jupyterhub"
  requests:
    memory: "3024Mi"
    cpu: "100m"
  limits:
    memory: "5024Mi"
    cpu: "300m"
  volume:
    pvcName: "dev-jupyterhub-pvc"
    name: "dev-jupyterhub-notebook-storage"
    storage: "50Gi"

fairscape:
  pullSecretName: "ghcr-pull-secret"
  minio:
    image: quay.io/minio/minio:latest
    appName: minio-app
    serviceName: incluster-minio
    servicePort: 9000
    serviceTargetPort: 9000
    prod:
      secretName: "prod-minio-secret"
      bucketName: "clarklab"
    test:
      secretName: "test-minio-secret"
      bucketName: "test"
    requests:
      memory: "4024Mi"
      cpu: "500m"
    limits:
      memory: "8024Mi"
      cpu: "1000m"
    volume:
      storageClassName: "clarklab-sc"
      volumeName: "clarklab-nfs-pv"
      pvcName: "minio-prod-research-project-pvc"
      storage: "300Gi"

  backend:
    image: "ghcr.io/fairscape/mds_python:RELEASE.2025-07-17.v3"
    testImage: "ghcr.io/fairscape/mds_python:release.2025-07-17.v3"
    appName: "backend-app"
    serviceName: "backend-service"
    servicePort: 8080
    serviceTargetPort: 8080
    requests:
      memory: "4024Mi"
      cpu: "500m"
    limits:
      memory: "8024Mi"
      cpu: "1000m"
  frontend:
    image: "ghcr.io/fairscape/fairscapefrontend:RELEASE.2025-07-08.v4"
    testImage: "ghcr.io/fairscape/fairscapefrontend:RELEASE.2025-07-08.v4"
    appName: "fairscape-frontend-app"
    serviceName: "frontend-service"
    servicePort: 80
    serviceTargetPort: 80
    requests:
      memory: "2024Mi"
      cpu: "500m"
    limits:
      memory: "4024Mi"
      cpu: "700m"
  worker:
    image: "ghcr.io/fairscape/mds_python:RELEASE.2025-07-17.v3"
    testImage: "ghcr.io/fairscape/mds_python:release.2025-07-17.v3"
    appName: "fairscape-worker-app"
    requests:
      memory: "4024Mi"
      cpu: "500m"
    limits:
      memory: "6024Mi"
      cpu: "800m"
  search:
    image: "ghcr.io/fairscape/semantic_search:RELEASE.2025-06-20.v2"
    servicePort: 5050
    serviceTargetPort: 5050
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "7Gi"
      cpu: "1000m"

redis:
  image: "redis:7.0.15-alpine3.20"
  serviceName: "prod-redis-service"
  servicePort: 6379
  prod:
    jobDB: "0"
    resultDB: "1"
  test:
    jobDB: "2"
    resultDB: "3"
  jobDatabase: "0"
  resultDatabase: "1"
  requests:
    memory: "2000Mi"
    cpu: "200m"
  limits:
    memory: "3000Mi"
    cpu: "300m"

mongo_express:
  image: "mongo-express"
  serviceName: "mongo-express-service"
  appName: "mongo-express"
  servicePort: 8081
  serviceTargetPort: 8081
  requests:
    memory: "2000Mi"
    cpu: "1000m"
  limits:
    memory: "3000Mi"
    cpu: "2000m"
  secretName: "me-secret"

mongo:
  hostURI: "prod-mongo-psmdb-db-rs0.clarklab.svc.cluster.local"
  port: "27017"
  test:
    db: "test"
    username:
      secretName: "mongo-test-secret"
      secretKey: "username"
    password:
      secretName: "mongo-test-secret"
      secretKey: "password"
  prod:
    db: "clarklab"
    username:
      secretName: "mongo-prod-secret"
      secretKey: "username"
    password:
      secretName: "mongo-prod-secret"
      secretKey: "password"

minio:
  serviceName: "minio.uvarc.io"
  accessKey:
    secretName: minio-secret
    secretKey: username
  secretKey:
    secretName: minio-secret
    secretKey: password

chromadb:
  image: "chromadb/chroma:1.0.12"
  appName: "test-chromadb"
  serviceName: "test-chromadb-service"
  servicePort: 8000
  containerPort: 8000
  requests:
    memory: "1Gi"
    cpu: "200m"
  limits:
    memory: "2Gi"
    cpu: "500m"

fairscapeConfig:
  env:
    - name: "FAIRSCAPE_HOST"
      value: "fairscape.net"
    - name: "FAIRSCAPE_PORT"
      value: "8080"
    - name: "FAIRSCAPE_LDAP_PORT"
      value: "1389"
    - name: "FAIRSCAPE_MONGO_PORT"
      value: "27017"
    - name: "FAIRSCAPE_MONGO_IDENTIFIER_COLLECTION"
      value: "fairscape"
    - name: "FAIRSCAPE_MONGO_USER_COLLECTION"
      value: "users"
    - name: "FAIRSCAPE_MONGO_ROCRATE_COLLECTION"
      value: "rocrate"
    - name: "FAIRSCAPE_MINIO_URI"
      value: http://incluster-minio:9000
    - name: "FAIRSCAPE_MINIO_SECURE"
      value: "True"
    - name: "FAIRSCAPE_MINIO_CERT_CHECK"
      value: "False"
    - name: "FAIRSCAPE_MINIO_DEFAULT_BUCKET_PATH"
      value: "default"
    - name: "FAIRSCAPE_MINIO_ROCRATE_BUCKET_PATH"
      value: "rocrate"
    - name: "FAIRSCAPE_NAAN"
      value: "59852"
    - name: "FAIRSCAPE_URL"
      value: "https://fairscape.net"
