namespace: "clarklab"

jupyterhub:
  image: "jupyter/datascience-notebook:latest"
  serviceName: "dev-jupyterhub"
  servicePort: 8080
  serviceTargetPort: 8080
  deploymentName: "dev-jupyterhub-deployment"
  appName: "dev-jupyterhub"
  requests:
    memory: "3024Mi"
    cpu: "100m"
  limits:
    memory: "5024Mi"
    cpu: "300m"
  volume:
    pvcName: "dev-jupyterhub-pvc"
    name: "dev-jupyterhub-notebook-storage"
    storage: "10Gi"

fairscape:
  backend: 
    image: "ghcr.io/fairscape/mds_python:RELEASE.2025-01-13.v4"
    appName: "prod-backend-app"
    serviceName: "prod-backend-service"
    servicePort: 8080
    serviceTargetPort: 8080
    requests:
      memory: "4024Mi"
      cpu: "500m"
    limits:
      memory: "8024Mi"
      cpu: "1000m"
  frontend:
    image: "ghcr.io/fairscape/fairscapefrontend:release.2024-12-18"
    appName: "prod-fairscape-frontend-app"
    serviceName: "prod-frontend-service"
    servicePort: 80
    serviceTargetPort: 80
    requests:
      memory: "2024Mi"
      cpu: "500m"
    limits:
      memory: "4024Mi"
      cpu: "700m"
  worker:
    image: "ghcr.io/fairscape/mds_python:RELEASE.2025-01-13.v4"
    appName: "prod-fairscape-worker-app"
    requests:
      memory: "4024Mi"
      cpu: "500m"
    limits:
      memory: "6024Mi"
      cpu: "800m"
    volume:
      name: "prod-fairscape-worker-scratch-volume"
      pvcName: "prod-fairscape-worker-scratch-pvc"
      storage: "30Gi"

redis:
  image: "redis:7.0.15-alpine3.20"
  serviceName: "prod-redis-service"
  servicePort: 6379
  jobDatabase: "0"
  resultDatabase: "1"
  requests:
    memory: "2000Mi"
    cpu: "200m"
  limits:
    memory: "3000Mi"
    cpu: "300m"

ldap:  
  appName: "prod-ldap"
  requests:
    memory: "2024Mi"
    cpu: "500m"
  limits:
    memory: "3024Mi"
    cpu: "800m"
  image: "bitnami/openldap:2.6.8"
  serviceName: "prod-ldap-service"
  servicePort: 1389
  env:
    LDAP_ROOT: "dc=fairscape,dc=net"
    LDAP_ADMIN_USERNAME: "fairscapeAdmin"
    LDAP_ADMIN_PASSWORD: "fairscapeAdminPassword"
    LDAP_ADMIN_DN: "cn=admin,dc=fairscape,dc=net"
    LDAP_CONFIG_ADMIN_ENABLED: "yes"
    LDAP_CONFIG_ADMIN_USERNAME: "configAdmin"
    LDAP_CONFIG_ADMIN_PASSWORD: "configAdminPassword"
    LDAP_USER_DC: "users"
    LDAP_GROUP: "admins"
    LDAP_USERS: "fairscapeUser"
    LDAP_PASSWORDS: "fairscapePass"


mongo:
  image: "docker.io/mongo:7.0.13-rc1"
  appName: "prod-mongo"
  deploymentName: "prod-mongo-deployment"
  serviceName: "mongo-prod-service"
  servicePort: 27017
  pvc:
    name: "mongo-prod-pvc"
    requests:
      storage: 10Gi
  requests:
    memory: "4024Mi"
    cpu: "250m"
  limits:
    memory: "6024Mi"
    cpu: "500m"
  accessKey:
    secretName: "fairscape-secrets"
    secretKey: mongo-access-key
  secretKey:
    secretName: "fairscape-secrets"
    secretKey: mongo-secret-key

minio:  
  serviceName: "minio.uvarc.io"
  accessKey:
    secretName: fairscape-secrets
    secretKey: minio-access-key
  secretKey:
    secretName: fairscape-secrets
    secretKey: minio-secret-key

fairscapeConfig:
  env:
    - name: "FAIRSCAPE_HOST"
      value: "fairscape.net"
    - name: "FAIRSCAPE_PORT"
      value: "8080"
    - name: "FAIRSCAPE_LDAP_HOST"
      value: "prod-ldap-service"
    - name: "FAIRSCAPE_LDAP_PORT"
      value: "1389"
    - name: "FAIRSCAPE_LDAP_ADMIN_DN"
      value: "cn=fairscapeAdmin,dc=fairscape,dc=net"
    - name: "FAIRSCAPE_MONGO_HOST"
      value: "mongo-prod-service" 
    - name: "FAIRSCAPE_MONGO_PORT"
      value: "27017"
    - name: "FAIRSCAPE_MONGO_DATABASE"
      value: "clarklab"
    - name: "FAIRSCAPE_MONGO_IDENTIFIER_COLLECTION"
      value: "fairscape"
    - name: "FAIRSCAPE_MONGO_USER_COLLECTION"
      value: "users"
    - name: "FAIRSCAPE_MONGO_ROCRATE_COLLECTION"
      value: "rocrate"
    - name: "FAIRSCAPE_MINIO_SECURE"
      value: "True"
    - name: "FAIRSCAPE_MINIO_CERT_CHECK"
      value: "False"
    - name: "FAIRSCAPE_MINIO_DEFAULT_BUCKET"
      value: "clarklab"
    - name: "FAIRSCAPE_MINIO_DEFAULT_BUCKET_PATH"
      value: "default"
    - name: "FAIRSCAPE_MINIO_ROCRATE_BUCKET"
      value: "clarklab"
    - name: "FAIRSCAPE_MINIO_ROCRATE_BUCKET_PATH"
      value: "rocrate"
    - name: "FAIRSCAPE_NAAN"
      value: "59852"
    - name: FAIRSCAPE_LDAP_ADMIN_PASSWORD
      value: "fairscapeAdminPassword"
    - name: "FAIRSCAPE_LDAP_BASE_DN"
      value: "dc=fairscape,dc=net"
    - name: "FAIRSCAPE_LDAP_USERS_DN"
      value: "ou=users,dc=fairscape,dc=net"
    - name: "FAIRSCAPE_LDAP_GROUPS_DN"
      value: "ou=groups,dc=fairscape,dc=net"
    - name: "FAIRSCAPE_URL"
      value: "https://fairscape.net"
