namespace: "clarklab"

jupyterhub:
  image: "jupyter/datascience-notebook:latest"
  serviceName: "dev-jupyterhub"
  servicePort: 8080
  serviceTargetPort: 8080
  deploymentName: "dev-jupyterhub-deployment"
  appName: "dev-jupyterhub"
  resources:
    requests:
      memory: "3024Mi"
      cpu: "100m"
    limits:
      memory: "5024Mi"
      cpu: "300m"

fairscape:
  backend: 
    image: "ghcr.io/fairscape/mds_python:RELEASE.2024-08-02.v2"
    appName: "prod-fairscape-backend"
    servicePort: 8080
    serviceTargetPort: 8080
    resources:
      requests:
        memory: "4024Mi"
        cpu: "500m"
      limits:
        memory: "8024Mi"
        cpu: "1000m"
  frontend:
    image: "ghcr.io/fairscape/fairscapefrontend:RELEASE.2024-07-19"
    appName: "prod-fairscape-frontend"
    servicePort: 80
    serviceTargetPort: 80
    requests:
      memory: "2024Mi"
      cpu: "500m"
    limits:
      memory: "4024Mi"
      cpu: "700m"
  worker:
    image: "ghcr.io/fairscape/mds_python:RELEASE.2024-08-02.v2"
    appName: "prod-fairscape-worker"
    resources:
      requests:
        memory: "4024Mi"
        cpu: "500m"
      limits:
        memory: "6024Mi"
        cpu: "800m"

redis:
  image: "redis:7.0.15-alpine3.20"
  serviceName: "prod-redis-service"
  servicePort: 6379
  jobDatabase: "0"
  resultDatabase: "1"

ldap:  
  appName: "prod-ldap"
  requests:
    memory: "2024Mi"
    cpu: "500m"
  limits:
    memory: "3024Mi"
    cpu: "800m"
  image: "bitnami/openldap:2.6.8"
  serviceName: "prod-ldap-service"
  servicePort: 1389
  env:
    LDAP_ROOT: "dc=fairscape,dc=net"
    LDAP_ADMIN_USERNAME: "fairscapeAdmin"
    LDAP_ADMIN_PASSWORD: "fairscapeAdminPassword"
    LDAP_ADMIN_DN: "cn=admin,dc=fairscape,dc=net"
    LDAP_CONFIG_ADMIN_ENABLED: "yes"
    LDAP_CONFIG_ADMIN_USERNAME: "configAdmin"
    LDAP_CONFIG_ADMIN_PASSWORD: "configAdminPassword"
    LDAP_USER_DC: "users"
    LDAP_GROUP: "admins"
    LDAP_USERS: "fairscapeUser"
    LDAP_PASSWORDS: "fairscapePass"


mongo:
  image: "mongo:latest"
  appName: "prod-mongo"
  deploymentName: "prod-mongo-deployment"
  serviceName: "mongo-prod-service"
  servicePort: 27017
  pvc:
    name: "mongo-prod-pvc"
    requests:
      storage: 10Gi
  requests:
    memory: "4024Mi"
    cpu: "250m"
  limits:
    memory: "6024Mi"
    cpu: "500m"
  accessKey:
    secretName: "fairscape-secrets"
    secretKey: mongo-access-key
  secretKey:
    secretName: "fairscape-secrets"
    secretKey: mongo-secret-key

minio:  
  serviceName: "minio.uvarc.io"
  accessKey:
    secretName: fairscape-secrets
    secretKey: minio-access-key
  secretKey:
    secretName: fairscape-secrets
    secretKey: minio-secret-key

fairscapeConfig:
  env:
    - name: FAIRSCAPE_MONGO_DATABASE 
      value: "clarklab"
    - name: FAIRSCAPE_MONGO_IDENTIFIER_COLLECTION
      value: "fairscape"
    - name: FAIRSCAPE_MONGO_USER_COLLECTION
      value: "users"
    - name: FAIRSCAPE_MONGO_ROCRATE_COLLECTION
      value: "rocrate"
    - name: FAIRSCAPE_MINIO_SECURE
      value: "True"
    - name: FAIRSCAPE_MINIO_CERT_CHECK
      value: "False"
    - name: FAIRSCAPE_MINIO_DEFAULT_BUCKET
      value: "clarklab"
    - name: FAIRSCAPE_MINIO_DEFAULT_BUCKET_PATH
      value: "default"
    - name: FAIRSCAPE_MINIO_ROCRATE_BUCKET
      value: "clarklab"
    - name: FAIRSCAPE_MINIO_ROCRATE_BUCKET_PATH
      value: "rocrate"
    - name: FAIRSCAPE_NAAN
      value: "59852"
    - name: FAIRSCAPE_REDIS_HOST
      value: "prod-redis-service"
    - name: FAIRSCAPE_REDIS_PORT
      value: "6379"
    - name: FAIRSCAPE_LDAP_BASE_DN
      value: "dc=fairscape,dc=net"
    - name: FAIRSCAPE_LDAP_USERS_DN
      value: "ou=users,dc=fairscape,dc=net"
    - name: FAIRSCAPE_LDAP_GROUPS_DN
      value: "ou=groups,dc=fairscape,dc=net"

