jupyterhub:
  hub:
    labels:
      app: jupyterhub
    resources: 
      requests:
        memory: "1000Mi"
        cpu: "100m"
      limits:
        memory: "2000Mi"
        cpu: "200m"
  proxy:
    labels:
      app: jupyterhub
    chp:
      resources:
        requests:
          memory: "1000Mi"
          cpu: "100m"
        limits:
          memory: "2000Mi"
          cpu: "200m"
    service:
      type: ClusterIP
  prePuller:
    continuous:
      enabled: false
    hook:
      enabled: false
    labels:
      app: jupyterhub
    resources:
      requests:
        memory: "0Mi"
        cpu: "0m"
      limits:
        memory: "0Mi"
        cpu: "0m"
  scheduling:
    userScheduler:
      enabled: true
      replicas: 1
      resources:
        requests:
          memory: "1000Mi"
          cpu: "100m"
        limits:
          memory: "2000Mi"
          cpu: "200m"
    userPlaceholder:
      enabled: false 